version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
install:
- cmd: git submodule -q update --init
build_script:
- cmd: |-
    rem flips
    cd flips
    type make.bat | find /v "vcvars" | find /v "goto h" > make-cleaned.bat
    call make-cleaned.bat
    ren COPYING copying-flips.txt
    ren COPYING.gpl3 copying.gpl3-flips.txt
    cd ..
    7z a tools.7z .\flips\flips.exe .\flips\copying*.txt

    rem BMP2Tile
    msbuild bmp2tile\source\BMP2Tile.sln /m /p:Platform=x86;Configuration=Release
    ren bmp2tile\readme.md readme_bmp2tile.md
    ren bmp2tile\LICENSE license_bmp2tile.txt
    7z a tools.7z .\bmp2tile\bmp2tile.exe .\bmp2tile\readme_bmp2tile.md .\bmp2tile\license_bmp2tile.txt

    rem compressor DLLs
    msbuild bmp2tilecompressors\compressors\tilecompressordlls.sln /m /p:Platform=x86;Configuration=Release
    7z a tools.7z .\bmp2tilecompressors\compressors\Release\*.dll

    rem WLA DX
    cd wla-dx
    cmake .
    cmake --build . --config Release --target wlalink
    cmake --build . --config Release --target wla-z80
    cd ..
    ren wla-dx\LICENSE license_wladx.txt
    ren wla-dx\readme.md readme_wladx.md
    7z a tools.7z .\wla-dx\binaries\Release\wlalink.exe .\wla-dx\binaries\Release\wla-z80.exe .\wla-dx\license_wladx.txt .\wla-dx\readme_wladx.md

    rem PSGTool
    ren PSGTool\License.txt license_PSGTool.txt
    ren PSGTool\readme.txt readme_PSGTool.txt
    7z a tools.7z .\PSGTool\PSGTool.jar .\PSGTool\license_PSGTool.txt .\PSGTool\readme_PSGTool.txt psgtool.cmd
    
    rem Compile.bat
    7z a tools.7z Compile.bat
artifacts:
- path: '*.7z'
  name: Package
deploy:
- provider: GitHub
  auth_token:
    secure: KbY6wD6RTuotJxi7BdGQWg4e6rEc9OMP1u0keEYIrO9CrV9C8OJNSTjaOAmNH1LJ
  artifact: Package