version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: |-
    rem flips
    cd flips
    call "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\vc\Auxiliary\Build\vcvars32.bat"
    echo.>strings.h
    cl /O2 /MT /EHsc *.cpp libdivsufsort-2.0.1\lib\*.c /Ilibdivsufsort-2.0.1\include\ /I. /DHAVE_CONFIG_H /link /out:flips.exe shell32.lib comctl32.lib comdlg32.lib Advapi32.lib User32.lib gdi32.lib
    ren COPYING flips.copying.txt
    ren COPYING.gpl3 flips.copying.gpl3.txt
    cd ..
    7z a tools.7z .\flips\flips.exe .\flips\flips.copying.txt .\flips\flips.copying.gpl3.txt

    rem BMP2Tile
    msbuild bmp2tile\source\BMP2Tile.sln /m /p:Platform=x86;Configuration=Release
    ren bmp2tile\readme.md bmp2tile.readme.md
    ren bmp2tile\LICENSE bmp2tile.license.txt
    7z a tools.7z .\bmp2tile\bmp2tile.exe .\bmp2tile\bmp2tile.readme.md .\bmp2tile\bmp2tile.license.txt

    rem compressor DLLs
    msbuild bmp2tilecompressors\compressors\tilecompressordlls.sln /m /p:Platform=x86;Configuration=Release
    ren bmp2tilecompressors\LICENSE bmp2tilecompressors.license.txt
    7z a tools.7z .\bmp2tilecompressors\compressors\Release\*.dll .\bmp2tilecompressors\bmp2tilecompressors.license.txt

    rem WLA DX
    cd wla-dx
    cmake -A x64 -T host=x64 .
    cmake --build . --config Release --target wlalink --target wla-z80
    cd ..
    ren wla-dx\LICENSE wladx.license.txt
    ren wla-dx\readme.md wladx.readme.md
    7z a tools.7z .\wla-dx\binaries\Release\wlalink.exe .\wla-dx\binaries\Release\wla-z80.exe .\wla-dx\wladx.license.txt .\wla-dx\wladx.readme.md

    rem PSGTool
    ren PSGTool\License.txt PSGTool.license.txt
    ren PSGTool\readme.txt PSGTool.readme.txt
    7z a tools.7z .\PSGTool\PSGTool.jar .\PSGTool\PSGTool.license.txt .\PSGTool\PSGTool.readme.txt psgtool.cmd
    
    rem Compile.bat
    7z a tools.7z Compile.bat
    
    rem make
    7z a tools.7z .\make\*

artifacts:
- path: '*.7z'
  name: Package
deploy:
- provider: GitHub
  auth_token:
    secure: rKUfRHMGs7wVh/SYX9kJ67VqiPlztPwvnh3yjC3C2NX/Wpn9XsZrxIx0BXe9ZztT
  artifact: Package
  on:
    branch: master